# -*- coding: utf-8 -*-
"""Huấn_luyện_Mô_hình_Dự_đoán_Thời_tiết.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K81Jo2wrz42laiD211OW7zUBPJnvzpVk
"""

import os
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.preprocessing import image_dataset_from_directory
from sklearn.metrics import classification_report, confusion_matrix

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

from google.colab import drive
drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/dataset.zip'
extract_path = '/content/dataset'

print("Đang giải nén dữ liệu...")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
print("Giải nén hoàn tất!")

data_dir = '/content/dataset/dataset'

BATCH_SIZE = 32
IMG_SIZE = (300, 300)

# Tập Huấn luyện (80%)
train_dataset = image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# Tập Validation (20%)
val_dataset = image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_dataset.class_names
print("Các nhãn phân loại:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_dataset = train_dataset.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_dataset = val_dataset.cache().prefetch(buffer_size=AUTOTUNE)

class_counts = {}
for class_name in class_names:
    class_path = os.path.join(data_dir, class_name)
    class_counts[class_name] = len(os.listdir(class_path))

plt.figure(figsize=(12, 6))
sns.barplot(x=list(class_counts.keys()), y=list(class_counts.values()), palette="viridis")
plt.title('Số lượng hình ảnh trong mỗi phân lớp thời tiết')
plt.xlabel('Thời tiết')
plt.ylabel('Số lượng ảnh')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10, 10))
for images, labels in train_dataset.take(1):
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].numpy().astype("uint8"))
        plt.title(class_names[labels[i]])
        plt.axis("off")
plt.show()

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"), # Lật ngang
    tf.keras.layers.RandomRotation(0.2),      # Xoay góc 20%
    tf.keras.layers.RandomZoom(0.2),          # Phóng to/thu nhỏ
])

model = models.Sequential([
    layers.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),

    data_augmentation,
    layers.Rescaling(1./255),

    layers.Conv2D(32, (3, 3), padding='same'),
    layers.BatchNormalization(), # Thêm Batch Norm giúp huấn luyện ổn định và nhanh hơn
    layers.Activation('relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(64, (3, 3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(128, (3, 3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D(2, 2),

    layers.Conv2D(256, (3, 3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.MaxPooling2D(2, 2),
    layers.Dropout(0.4),

    layers.GlobalAveragePooling2D(),

    layers.Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    layers.Dropout(0.5),

    layers.Dense(len(class_names), activation='softmax')
])

model.summary()

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
num_classes = len(class_names)
model.compile(optimizer=optimizer,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True),
    tf.keras.callbacks.ModelCheckpoint('best_weather_model.keras', save_best_only=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.3, patience=3, min_lr=1e-6, verbose=1)
]

EPOCHS = 50

print("Bắt đầu huấn luyện...")
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=EPOCHS,
    callbacks=callbacks
)

conv_layers = [layer for layer in model.layers if isinstance(layer, layers.Conv2D)]

activation_model = models.Model(inputs=model.inputs, outputs=[layer.output for layer in conv_layers])

for images, labels in val_dataset.take(1):
    sample_img = images[0]
    break

img_array = tf.expand_dims(sample_img, 0)
activations = activation_model.predict(img_array)

first_layer_activation = activations[0]

plt.figure(figsize=(15, 10))
for i in range(16):
    plt.subplot(4, 4, i+1)
    plt.imshow(first_layer_activation[0, :, :, i], cmap='viridis')
    plt.axis('off')

plt.suptitle('Feature Maps của lớp Conv2D đầu tiên', fontsize=16)
plt.show()

print(history.history.keys())

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs_range = range(len(acc))

plt.figure(figsize=(14, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')

plt.show()

y_true = []
y_pred_probs = []

print("Đang dự đoán trên tập validation...")
for images, labels in val_dataset:
    y_true.extend(labels.numpy())
    preds = model.predict(images, verbose=0)
    y_pred_probs.extend(preds)

y_true = np.array(y_true)
y_pred = np.argmax(y_pred_probs, axis=1)

print("\nBÁO CÁO PHÂN LOẠI (Classification Report):")
print(classification_report(y_true, y_pred, target_names=class_names))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

def predict_weather(img_path):
    img = tf.keras.utils.load_img(img_path, target_size=IMG_SIZE)
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)

    predictions = model.predict(img_array)
    score = tf.nn.softmax(predictions[0])

    predicted_class = class_names[np.argmax(score)]
    confidence = 100 * np.max(score)

    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Dự đoán: {predicted_class} ({confidence:.2f}%)")
    plt.show()

predict_weather('/content/dataset/dataset/rain/1534.jpg')

final_model_path = '/content/drive/MyDrive/DeepLearning/weather_classification_model.h5'
model.save(final_model_path)
print(f"Mô hình đã được lưu tại: {final_model_path}")