# -*- coding: utf-8 -*-
"""weather_classification_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3kt0iOKy8fUvCMY31oZgfoDiJ9sRR9U

# 🌤️ Weather Image Classification using Improved CNN
**Dataset:** 11-class weather dataset từ Google Drive  
**Image size:** 300x300  
**Split:** 80% Train / 20% Validation

## 1. Mount Google Drive & Kiểm tra Dataset
"""

from google.colab import drive
drive.mount('/content/drive')

import os

DATASET_PATH = '/content/drive/MyDrive/dataset'

# Liệt kê các class (folder) trong dataset
classes = sorted([d for d in os.listdir(DATASET_PATH)
                  if os.path.isdir(os.path.join(DATASET_PATH, d))])
print(f"Số lượng class: {len(classes)}")
print(f"Các class: {classes}")

# Đếm số ảnh mỗi class
print("\nSố ảnh mỗi class:")
total = 0
for cls in classes:
    cls_path = os.path.join(DATASET_PATH, cls)
    imgs = [f for f in os.listdir(cls_path)
            if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.webp'))]
    print(f"  {cls}: {len(imgs)} ảnh")
    total += len(imgs)
print(f"\nTổng cộng: {total} ảnh")

"""## 2. Cài đặt thư viện & Import"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
)
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, precision_score, recall_score, f1_score
)

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {len(tf.config.list_physical_devices('GPU')) > 0}")

"""## 3. Cấu hình Hyperparameters"""

# ===== CẤU HÌNH =====
IMG_SIZE     = 300          # Kích thước ảnh 300x300
BATCH_SIZE   = 32
EPOCHS       = 50
NUM_CLASSES  = 11
SEED         = 42
VAL_SPLIT    = 0.2          # 20% validation
LEARNING_RATE = 1e-3
DROPOUT_RATE  = 0.4
L2_REG        = 1e-4

MODEL_SAVE_PATH = '/content/drive/MyDrive/weather_cnn_best.keras'

print("Cấu hình đã được thiết lập!")

"""## 4. Data Augmentation & Chuẩn bị Dataset"""

# Data augmentation cho tập train
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=VAL_SPLIT,
    rotation_range=20,
    width_shift_range=0.15,
    height_shift_range=0.15,
    shear_range=0.10,
    zoom_range=0.15,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

# Validation chỉ rescale, không augment
val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=VAL_SPLIT
)

train_generator = train_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    seed=SEED,
    shuffle=True
)

val_generator = val_datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    seed=SEED,
    shuffle=False
)

CLASS_NAMES = list(train_generator.class_indices.keys())
print(f"\nClasses: {CLASS_NAMES}")
print(f"Train samples: {train_generator.samples}")
print(f"Validation samples: {val_generator.samples}")

"""## 5. Visualize một số ảnh mẫu"""

images, labels = next(train_generator)

fig, axes = plt.subplots(3, 6, figsize=(18, 9))
fig.suptitle('Mẫu ảnh từ tập Train (sau augmentation)', fontsize=14, fontweight='bold')

for i, ax in enumerate(axes.flat):
    if i < len(images):
        ax.imshow(images[i])
        label_idx = np.argmax(labels[i])
        ax.set_title(CLASS_NAMES[label_idx], fontsize=8)
    ax.axis('off')

plt.tight_layout()
plt.show()

"""## 6. Xây dựng Mô hình CNN Cải tiến

Kiến trúc sử dụng:
- **Depthwise Separable Convolution** (tiết kiệm tham số)
- **Residual-style skip connections** (tránh vanishing gradient)
- **Batch Normalization** sau mỗi conv
- **Global Average Pooling** thay vì Flatten
- **L2 Regularization + Dropout** (chống overfitting)
"""

def conv_block(x, filters, kernel_size=3, strides=1, use_residual=False):
    """Conv Block: Conv -> BN -> ReLU (với tùy chọn residual)"""
    shortcut = x

    x = layers.Conv2D(
        filters, kernel_size, strides=strides, padding='same',
        kernel_regularizer=regularizers.l2(L2_REG), use_bias=False
    )(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)

    x = layers.Conv2D(
        filters, kernel_size, padding='same',
        kernel_regularizer=regularizers.l2(L2_REG), use_bias=False
    )(x)
    x = layers.BatchNormalization()(x)

    # Residual connection
    if use_residual:
        if shortcut.shape[-1] != filters or strides != 1:
            shortcut = layers.Conv2D(
                filters, 1, strides=strides, padding='same', use_bias=False
            )(shortcut)
            shortcut = layers.BatchNormalization()(shortcut)
        x = layers.Add()([x, shortcut])

    x = layers.Activation('relu')(x)
    return x


def build_improved_cnn(input_shape=(300, 300, 3), num_classes=11):
    inputs = keras.Input(shape=input_shape)

    # ── Stage 1: Stem ──────────────────────────────────────────
    x = layers.Conv2D(32, 3, strides=2, padding='same', use_bias=False)(inputs)  # 150x150
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Conv2D(64, 3, padding='same', use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.MaxPooling2D(2)(x)  # 75x75

    # ── Stage 2: 128 filters ────────────────────────────────────
    x = conv_block(x, 128, use_residual=True)  # 75x75
    x = layers.MaxPooling2D(2)(x)              # 37x37
    x = layers.Dropout(0.2)(x)

    # ── Stage 3: 256 filters ────────────────────────────────────
    x = conv_block(x, 256, use_residual=True)  # 37x37
    x = layers.MaxPooling2D(2)(x)              # 18x18
    x = layers.Dropout(0.25)(x)

    # ── Stage 4: 512 filters ────────────────────────────────────
    x = conv_block(x, 512, use_residual=True)  # 18x18
    x = layers.MaxPooling2D(2)(x)              # 9x9
    x = layers.Dropout(0.3)(x)

    # ── Stage 5: 512 filters ────────────────────────────────────
    x = conv_block(x, 512, use_residual=True)  # 9x9
    x = layers.Dropout(0.3)(x)

    # ── Head ────────────────────────────────────────────────────
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(512, kernel_regularizer=regularizers.l2(L2_REG))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(DROPOUT_RATE)(x)

    x = layers.Dense(256, kernel_regularizer=regularizers.l2(L2_REG))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(DROPOUT_RATE)(x)

    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = keras.Model(inputs, outputs, name='WeatherCNN_Improved')
    return model


model = build_improved_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 3), num_classes=NUM_CLASSES)
model.summary()

"""## 7. Compile Mô hình"""

optimizer = keras.optimizers.Adam(
    learning_rate=LEARNING_RATE,
    weight_decay=1e-5
)

model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=[
        'accuracy',
        keras.metrics.Precision(name='precision'),
        keras.metrics.Recall(name='recall')
    ]
)

print(f"Tổng tham số: {model.count_params():,}")

"""## 8. Callbacks"""

callbacks = [
    # Lưu model tốt nhất theo val_accuracy
    ModelCheckpoint(
        filepath=MODEL_SAVE_PATH,
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    # Giảm LR khi val_loss không cải thiện
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-7,
        verbose=1
    ),
    # Dừng sớm nếu val_accuracy không cải thiện
    EarlyStopping(
        monitor='val_accuracy',
        patience=12,
        restore_best_weights=True,
        verbose=1
    )
]

print("Callbacks đã sẵn sàng!")

"""## 9. Huấn luyện Mô hình"""

history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=val_generator,
    callbacks=callbacks,
    verbose=1
)

print("\nHuấn luyện hoàn tất!")

"""## 10. Vẽ đồ thị Loss & Accuracy"""

def plot_history(history):
    fig, axes = plt.subplots(1, 2, figsize=(16, 5))
    fig.suptitle('Lịch sử Huấn luyện', fontsize=14, fontweight='bold')

    # Accuracy
    axes[0].plot(history.history['accuracy'], label='Train Accuracy', color='royalblue', linewidth=2)
    axes[0].plot(history.history['val_accuracy'], label='Val Accuracy', color='tomato', linewidth=2)
    axes[0].set_title('Accuracy theo Epoch')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    # Loss
    axes[1].plot(history.history['loss'], label='Train Loss', color='royalblue', linewidth=2)
    axes[1].plot(history.history['val_loss'], label='Val Loss', color='tomato', linewidth=2)
    axes[1].set_title('Loss theo Epoch')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig('/content/training_history.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Đã lưu biểu đồ tại /content/training_history.png")

plot_history(history)

"""## 11. Đánh giá Mô hình (Metrics đầy đủ)"""

# Reset generator về đầu để predict
val_generator.reset()

# Predict toàn bộ validation set
print("Đang dự đoán validation set...")
y_pred_proba = model.predict(val_generator, verbose=1)
y_pred = np.argmax(y_pred_proba, axis=1)
y_true = val_generator.classes

print(f"\nSố mẫu validation: {len(y_true)}")
print(f"Classes: {CLASS_NAMES}")

# ── Metrics tổng quát ──────────────────────────────────────────────
acc       = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall    = recall_score(y_true, y_pred, average='weighted')
f1        = f1_score(y_true, y_pred, average='weighted')

print("=" * 50)
print("       KẾT QUẢ ĐÁNH GIÁ MÔ HÌNH")
print("=" * 50)
print(f"  Accuracy  (tổng): {acc:.4f}  ({acc*100:.2f}%)")
print(f"  Precision (weighted): {precision:.4f}")
print(f"  Recall    (weighted): {recall:.4f}")
print(f"  F1-Score  (weighted): {f1:.4f}")
print("=" * 50)

# ── Classification Report (per-class) ─────────────────────────────
print("\nClassification Report (Accuracy / Precision / Recall / F1 / Support theo từng class):")
print(classification_report(
    y_true, y_pred,
    target_names=CLASS_NAMES,
    digits=4
))

"""## 12. Confusion Matrix"""

cm = confusion_matrix(y_true, y_pred)

fig, axes = plt.subplots(1, 2, figsize=(20, 8))

# Confusion Matrix (số lượng)
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
    ax=axes[0], linewidths=0.5
)
axes[0].set_title('Confusion Matrix (số lượng)', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Predicted Label', fontsize=11)
axes[0].set_ylabel('True Label', fontsize=11)
axes[0].tick_params(axis='x', rotation=45)
axes[0].tick_params(axis='y', rotation=0)

# Confusion Matrix (tỷ lệ %)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
sns.heatmap(
    cm_norm, annot=True, fmt='.2f', cmap='Greens',
    xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
    ax=axes[1], linewidths=0.5
)
axes[1].set_title('Confusion Matrix (tỷ lệ)', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Predicted Label', fontsize=11)
axes[1].set_ylabel('True Label', fontsize=11)
axes[1].tick_params(axis='x', rotation=45)
axes[1].tick_params(axis='y', rotation=0)

plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print("Đã lưu confusion matrix tại /content/confusion_matrix.png")

"""## 13. Biểu đồ Metrics theo từng Class"""

from sklearn.metrics import precision_recall_fscore_support

precision_per, recall_per, f1_per, support_per = precision_recall_fscore_support(
    y_true, y_pred, labels=range(NUM_CLASSES)
)

x = np.arange(len(CLASS_NAMES))
width = 0.25

fig, ax = plt.subplots(figsize=(16, 6))
bars1 = ax.bar(x - width, precision_per, width, label='Precision', color='steelblue', alpha=0.85)
bars2 = ax.bar(x,         recall_per,    width, label='Recall',    color='seagreen',  alpha=0.85)
bars3 = ax.bar(x + width, f1_per,        width, label='F1-Score',  color='tomato',    alpha=0.85)

ax.set_xlabel('Class', fontsize=12)
ax.set_ylabel('Score', fontsize=12)
ax.set_title('Precision / Recall / F1-Score theo từng Class', fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES, rotation=30, ha='right')
ax.set_ylim(0, 1.1)
ax.legend()
ax.grid(axis='y', alpha=0.3)

# Ghi giá trị lên cột
for bar in [*bars1, *bars2, *bars3]:
    h = bar.get_height()
    ax.annotate(f'{h:.2f}', xy=(bar.get_x() + bar.get_width()/2, h),
                xytext=(0, 2), textcoords='offset points',
                ha='center', va='bottom', fontsize=7)

plt.tight_layout()
plt.savefig('/content/metrics_per_class.png', dpi=150, bbox_inches='tight')
plt.show()

# Bảng Support
print("\nSupport (số mẫu thực tế trong validation) theo từng class:")
for cls, sup in zip(CLASS_NAMES, support_per):
    print(f"  {cls:<25} {int(sup)} mẫu")

"""## 14. Dự đoán thử trên ảnh mẫu"""

from tensorflow.keras.preprocessing import image as keras_image

def predict_single_image(img_path, model, class_names, img_size=300):
    """Dự đoán một ảnh và hiển thị top-3 kết quả"""
    img = keras_image.load_img(img_path, target_size=(img_size, img_size))
    x = keras_image.img_to_array(img) / 255.0
    x = np.expand_dims(x, axis=0)

    preds = model.predict(x, verbose=0)[0]
    top3_idx = np.argsort(preds)[::-1][:3]

    plt.figure(figsize=(5, 4))
    plt.imshow(img)
    title = f"Dự đoán: {class_names[top3_idx[0]]} ({preds[top3_idx[0]]*100:.1f}%)"
    plt.title(title, fontsize=11)
    plt.axis('off')
    plt.show()

    print("Top-3 dự đoán:")
    for i, idx in enumerate(top3_idx):
        print(f"  {i+1}. {class_names[idx]:<25} {preds[idx]*100:.2f}%")

# Lấy ảnh mẫu đầu tiên từ mỗi class để test
print("Demo dự đoán trên 3 ảnh ngẫu nhiên:")
import random
random.seed(SEED)

sample_paths = []
for cls in random.sample(CLASS_NAMES, min(3, len(CLASS_NAMES))):
    cls_dir = os.path.join(DATASET_PATH, cls)
    imgs_in_cls = [f for f in os.listdir(cls_dir)
                   if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    if imgs_in_cls:
        sample_paths.append(os.path.join(cls_dir, random.choice(imgs_in_cls)))

for path in sample_paths:
    print(f"\nẢnh: {path}")
    predict_single_image(path, model, CLASS_NAMES, IMG_SIZE)

"""## 15. Tóm tắt Kết quả"""

best_epoch = np.argmax(history.history['val_accuracy']) + 1
best_val_acc = max(history.history['val_accuracy'])

print("╔══════════════════════════════════════════════════╗")
print("║          TÓM TẮT KẾT QUẢ MÔ HÌNH              ║")
print("╠══════════════════════════════════════════════════╣")
print(f"║  Epoch tốt nhất       : {best_epoch:<24}║")
print(f"║  Val Accuracy cao nhất: {best_val_acc:.4f} ({best_val_acc*100:.2f}%)       ║")
print(f"║  Test Accuracy        : {acc:.4f} ({acc*100:.2f}%)       ║")
print(f"║  Precision (weighted) : {precision:.4f}                   ║")
print(f"║  Recall    (weighted) : {recall:.4f}                   ║")
print(f"║  F1-Score  (weighted) : {f1:.4f}                   ║")
print("╠══════════════════════════════════════════════════╣")
print(f"║  Model lưu tại: MyDrive/weather_cnn_best.keras  ║")
print("╚══════════════════════════════════════════════════╝")

"""## 16. Lưu model h5"""

model.save('content/drive/MyDrive/weather_cnn_best.h5')