# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utoNSOeMrEL7eG0p1XEeO1oNmVEbyWFb

Cấu hình thư viện và path dataset, size
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from itertools import cycle
import os

# Đường dẫn tới dataset. Ví dụ trên Colab Drive: "/content/drive/MyDrive/dataset"
DATA_DIR = "/content/drive/MyDrive/dataset"
BATCH_SIZE = 64
IMG_SIZE = (300, 300)

"""Nạp dữ liệu"""

print("=" * 60)
print("ĐANG NẠP DỮ LIỆU")
print("=" * 60)

print("Loading Training Data (80%)...")
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

print("Loading Validation Data (20%)...")
val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
num_classes = len(class_names)
print(f"Các lớp phân loại ({num_classes} lớp): {class_names}")

# Tối ưu pipeline nạp dữ liệu
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.prefetch(buffer_size=AUTOTUNE)

"""Tăng cường dữ liệu"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"), # Lật ngang
    tf.keras.layers.RandomRotation(0.2),      # Xoay góc 20%
    tf.keras.layers.RandomZoom(0.2),          # Phóng to/thu nhỏ
], name="data_augmentation")

"""Xây dựng mô hình Efficient-B3"""

print("\n" + "=" * 60)
print("XÂY DỰNG MÔ HÌNH EFFICIENTNET-B3")
print("=" * 60)


# include_top=False: bỏ lớp phân loại gốc (ImageNet 1000 class)
# weights='imagenet': dùng trọng số từ ImageNet (Transfer Learning)
base_model = tf.keras.applications.EfficientNetB3(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights='imagenet'
)

# PHASE 1 - Feature Extraction: Đóng băng toàn bộ base model
# Chỉ train các lớp Dense phía trên, tránh phá vỡ trọng số
base_model.trainable = False

# --- Xây dựng mô hình hoàn chỉnh bằng Functional API ---
inputs = tf.keras.Input(shape=IMG_SIZE + (3,))

# EfficientNet đã tích hợp normalization bên trong (không cần Rescaling thủ công)
x = data_augmentation(inputs)           # Augment (chỉ áp dụng lúc training)
x = tf.keras.applications.efficientnet.preprocess_input(x)  # Preprocess đúng chuẩn EfficientNet
x = base_model(x, training=False)       # BatchNorm dùng running stats
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.3)(x)    # Ngăn overfitting
x = tf.keras.layers.Dense(256, activation='relu')(x)  # Lớp ẩn thêm để học đặc trưng
x = tf.keras.layers.Dropout(0.3)(x)
outputs = tf.keras.layers.Dense(num_classes, activation='softmax')(x)

model = tf.keras.Model(inputs, outputs, name="EfficientNetB3_Weather")

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

"""FEATURE EXTRACTION Phase 1 Train lớp đầu"""

print("\n" + "=" * 60)
print("PHASE 1 - FEATURE EXTRACTION (Base model bị đóng băng)")
print("=" * 60)

EPOCHS_PHASE1 = 10  # Train nhanh, chỉ các lớp Dense

# Callback: dừng sớm nếu val_loss không cải thiện
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=3, restore_best_weights=True
)
# Callback: giảm learning rate nếu val_loss plateau
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.5, patience=2, min_lr=1e-7, verbose=1
)

history_phase1 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_PHASE1,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

"""PHASE 2 - FINE-TUNING (mở đóng băng một phần base model)"""

print("\n" + "=" * 60)
print("BƯỚC 4: PHASE 2 - FINE-TUNING (Mở đóng băng 30% lớp cuối)")
print("=" * 60)

# EfficientNet-B3 có tổng ~385 lớp
# Mở 30% lớp cuối để fine-tune (các lớp học đặc trưng cấp cao)
total_layers   = len(base_model.layers)
unfreeze_from  = int(total_layers * 0.7)   # Giữ nguyên 70% đầu, mở 30% cuối

print(f"Tổng số lớp của base model: {total_layers}")
print(f"Mở đóng băng từ lớp thứ {unfreeze_from} trở đi ({total_layers - unfreeze_from} lớp)")

base_model.trainable = True
for layer in base_model.layers[:unfreeze_from]:
    layer.trainable = False

# Giữ BatchNorm ở chế độ inference để tránh làm hỏng statistics
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

# Recompile với learning rate NHỎ HƠN rất nhiều để không phá vỡ trọng số
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),  # 100x nhỏ hơn Phase 1
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print(f"\nSố lớp có thể train sau fine-tuning: "
      f"{sum(1 for l in model.layers if l.trainable)}")

EPOCHS_PHASE2 = 10  # Fine-tune cần ít epoch hơn

early_stop_ft = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=4, restore_best_weights=True
)
reduce_lr_ft = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss', factor=0.5, patience=2, min_lr=1e-8, verbose=1
)

history_phase2 = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_PHASE2,
    callbacks=[early_stop_ft, reduce_lr_ft],
    verbose=1
)

"""Gộp 2 phase và trực quan hóa đồ thị accuracy, loss"""

print("\n" + "=" * 60)
print("BƯỚC 5: BIỂU ĐỒ QUÁ TRÌNH TRAINING")
print("=" * 60)

def combine_history(h1, h2, key):
    """Nối lịch sử training của 2 phase."""
    return h1.history[key] + h2.history[key]

acc      = combine_history(history_phase1, history_phase2, 'accuracy')
val_acc  = combine_history(history_phase1, history_phase2, 'val_accuracy')
loss     = combine_history(history_phase1, history_phase2, 'loss')
val_loss = combine_history(history_phase1, history_phase2, 'val_loss')

total_epochs = len(acc)
epochs_range = range(total_epochs)
phase2_start = len(history_phase1.history['accuracy'])  # Điểm bắt đầu Phase 2

plt.figure(figsize=(16, 6))

# --- Biểu đồ Accuracy ---
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc,     label='Train Accuracy',      linewidth=2, color='steelblue')
plt.plot(epochs_range, val_acc, label='Validation Accuracy', linewidth=2, color='orange', linestyle='--')
plt.axvline(x=phase2_start - 0.5, color='red', linestyle=':', linewidth=1.5,
            label=f'Fine-tuning bắt đầu (epoch {phase2_start})')
plt.legend(loc='lower right')
plt.title('Training & Validation Accuracy\n(EfficientNet-B3)', fontsize=13)
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.grid(True, alpha=0.3)

# --- Biểu đồ Loss ---
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss,     label='Train Loss',      linewidth=2, color='steelblue')
plt.plot(epochs_range, val_loss, label='Validation Loss', linewidth=2, color='orange', linestyle='--')
plt.axvline(x=phase2_start - 0.5, color='red', linestyle=':', linewidth=1.5,
            label=f'Fine-tuning bắt đầu (epoch {phase2_start})')
plt.legend(loc='upper right')
plt.title('Training & Validation Loss\n(EfficientNet-B3)', fontsize=13)
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("training_history.png", dpi=150, bbox_inches='tight')
plt.show()

"""Đánh giá trên tập Test"""

print("\n" + "=" * 60)
print("BƯỚC 6: ĐÁNH GIÁ MÔ HÌNH TRÊN TẬP TEST")
print("=" * 60)

print("Đang chạy dự đoán trên tập Validation...")
y_true       = []
y_pred_probs = []

for images, labels in val_ds:
    y_true.extend(labels.numpy())
    preds = model.predict(images, verbose=0)
    y_pred_probs.extend(preds)

y_true        = np.array(y_true)
y_pred_probs  = np.array(y_pred_probs)
y_pred_classes = np.argmax(y_pred_probs, axis=1)

test_loss, test_acc = model.evaluate(val_ds, verbose=0)
print(f"\n✅ Validation Accuracy : {test_acc:.4f} ({test_acc*100:.2f}%)")
print(f"✅ Validation Loss     : {test_loss:.4f}")

"""Báo cáo phân loại và Confusion matrix"""

print("\n" + "=" * 50)
print("BÁO CÁO PHÂN LOẠI (Precision, Recall, F1-Score)")
print("=" * 50)
print(classification_report(y_true, y_pred_classes, target_names=class_names))

print("\n" + "=" * 50)
print("Confusion matrix")
print("\n" + "=" * 50)
cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix - EfficientNet-B3')
plt.ylabel('Thực tế (True Label)')
plt.xlabel('Dự đoán (Predicted Label)')
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150, bbox_inches='tight')
plt.show()

"""Biểu đồ dưới đường cong"""

y_true_bin = label_binarize(y_true, classes=range(num_classes))

fpr     = dict()
tpr     = dict()
roc_auc = dict()
for i in range(num_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_pred_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(10, 8))
colors = cycle(['aqua', 'darkorange', 'cornflowerblue', 'green',
                'red', 'purple', 'brown', 'pink', 'gray', 'olive'])

for i, color in zip(range(num_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2,
             label=f'ROC {class_names[i]} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Multi-class ROC Curve - EfficientNet-B3')
plt.legend(loc="lower right", fontsize=9)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("roc_curve.png", dpi=150, bbox_inches='tight')
plt.show()

"""Lưu mô hình"""

model.save("weather_efficientnetb3_finetuned.keras")
print("\n✅ Đã lưu model (.keras): 'weather_efficientnetb3_finetuned.keras'")

# Định dạng .h5 (tương thích rộng rãi, dùng được với Keras cũ)
model.save("weather_efficientnetb3_finetuned.h5")
print("✅ Đã lưu model (.h5)   : 'weather_efficientnetb3_finetuned.h5'")

print("\n   Load lại .keras : tf.keras.models.load_model('weather_efficientnetb3_finetuned.keras')")
print("   Load lại .h5    : tf.keras.models.load_model('weather_efficientnetb3_finetuned.h5')")